cdef extern object (make_GF2E(GF2E_c (*)))
cdef extern object (make_GF2EX(GF2EX_c (*)))
cdef extern object (make_GF2X(GF2X_c (*)))
cdef extern object (make_ZZ(ZZ_c (*)))
cdef extern object (make_ZZ_p(ZZ_p_c (*)))
