"""
Catalog Of Crystal Models For (Tensor Products Of) Kirillov-Reshetikhin
Crystals
"""
from kirillov_reshetikhin import KirillovReshetikhinCrystal as KashiwaraNakashimaTableaux
from sage.combinat.rigged_configurations.rigged_configurations import RiggedConfigurations
from sage.combinat.rigged_configurations.kr_tableaux import KirillovReshetikhinTableaux
from sage.combinat.rigged_configurations.tensor_product_kr_tableaux import TensorProductOfKirillovReshetikhinTableaux
from littelmann_path import CrystalOfProjectedLevelZeroLSPaths as ProjectedLevelZeroLSPaths

