"""
Crystals

This is a catalog of crystals that are currently in Sage.
"""
from letters import CrystalOfLetters as Letters
from spins import CrystalOfSpins as Spins
from spins import CrystalOfSpinsPlus as SpinsPlus
from spins import CrystalOfSpinsMinus as SpinsMinus
from tensor_product import TensorProductOfCrystals as TensorProduct
from tensor_product import CrystalOfTableaux as Tableaux
from kyoto_path_model import KyotoPathModel
from fast_crystals import FastCrystal
from affine import AffineCrystalFromClassical
from affine import AffineCrystalFromClassicalAndPromotion
from kirillov_reshetikhin import KirillovReshetikhinCrystal as KirillovReshetikhin
from highest_weight_crystals import HighestWeightCrystal as HighestWeight
from direct_sum import DirectSumOfCrystals as DirectSum
from alcove_path import CrystalOfAlcovePaths as AlcovePaths
from littelmann_path import CrystalOfLSPaths as LSPaths
from littelmann_path import CrystalOfProjectedLevelZeroLSPaths as ProjectedLevelZeroLSPaths
from generalized_young_walls import CrystalOfGeneralizedYoungWalls as GeneralizedYoungWalls
from monomial_crystals import CrystalOfNakajimaMonomials as NakajimaMonomials
from sage.combinat.rigged_configurations.rigged_configurations import RiggedConfigurations
from sage.combinat.rigged_configurations.kr_tableaux import KirillovReshetikhinTableaux
from sage.combinat.rigged_configurations.tensor_product_kr_tableaux import TensorProductOfKirillovReshetikhinTableaux

import infinity_crystals_catalog as infinity
import elementary_crystals_catalog as elementary

