# Sage version information for Python scripts
# This file is auto-generated by the sage-update-version script, do not edit!
version = '8.4.beta4'
date = '2018-09-06'
banner = 'SageMath version 8.4.beta4, Release Date: 2018-09-06'
