# Sage version information for Python scripts
# This file is auto-generated by the sage-update-version script, do not edit!
version = '8.9.beta7'
date = '2019-08-18'
banner = 'SageMath version 8.9.beta7, Release Date: 2019-08-18'
