# Sage version information for Python scripts
# This file is auto-generated by the sage-update-version script, do not edit!
version = '9.7.beta7'
date = '2022-08-01'
banner = 'SageMath version 9.7.beta7, Release Date: 2022-08-01'
