#!/usr/bin/env bash

SAGE_APP_RESOURCES_DIR=`readlink -n "$0" 2> /dev/null` || \
SAGE_APP_RESOURCES_DIR=`realpath    "$0" 2> /dev/null` || \
SAGE_APP_RESOURCES_DIR="$0"

# Adjust for the $SAGE_ROOT to be used being one level deeper in the app bundle
SAGE_APP_RESOURCES_DIR="${SAGE_APP_RESOURCES_DIR%/*}/sage/"

# Work around spaces in the path (and perhaps cut down on location changes).
# We delete and recreate the symlink every time to ensure we are in the right place
rm -f /tmp/sage-map-app
ln -s "$SAGE_APP_RESOURCES_DIR" /tmp/sage-map-app
cd /tmp/sage-map-app

# Set (i.e. "source") SAGE_ROOT and all the other environment settings
echo Setting environment variables
. ./local/bin/sage-env # 1>/dev/null 2>/dev/null

# Mac OS X app bundles are *intended* to be moved around, and/or given away
# So always run first the respective script handling this
# (This should also catch Intel vs. PPC or 32Bit vs. 64Bit conflicts - untested)
echo Checking install location
./local/bin/sage-location

# TODO:
# handle dropped items
# optionally open a console session (based on environment variable?)
echo Starting notebook
"$SAGE_ROOT/sage" -notebook
