import padic_extension_generic_element

pAdicExtensionGenericElement = padic_extension_generic_element.pAdicExtensionGenericElement

class pAdicExtensionLazyGenericElement(pAdicExtensionGenericElement):
    pass
