import sage.rings.padics.padic_general_extension_generic_element

pAdicGeneralExtensionGenericElement = sage.rings.padics.padic_general_extension_generic_element.pAdicGeneralExtensionGenericElement

class pAdicGeneralExtensionAbsoluteElement(pAdicGeneralExtensionGenericElement):
    pass
