#!/bin/sh
if [ $# -ne 2 ]; then
    echo "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
    echo "Build SAGE package in the extcode directory."
    exit 0
fi

E=extcode
SAGE_VERSION=$1
SAGE_ROOT=$2
DIR=$E-$SAGE_VERSION

cd "$SAGE_ROOT/data/"
if [ -d $DIR ]; then
   rm -rf $DIR
fi
mkdir $DIR

cd $E
cp -pr * .hg .hgignore .hgtags "../$DIR/"
cd "../$DIR"
rm -f *.spkg
rm -f magma/*.dat magma/*.sig magma/*/*.dat magma/*/*.sig magma/*/*/*.dat magma/*/*/*.sig
rm -rf octave/user/tmp
rm -rf octave/user/*

cd ..
$SAGE_ROOT/sage -pkg $DIR
rm -rf $DIR
mv $DIR.spkg extcode
