#!/bin/sh
# This is the spkg-install script which will be emplaced within the SPKG for
# the extcode repository whenever it is packaged.

echo "Copying Extcode package to '$SAGE_ROOT/devel/ext-main'..."

if [ -d "$SAGE_ROOT/devel/ext-main" ]; then
    echo "Moving old Extcode package to '$SAGE_ROOT/devel/ext-main-old'..."
    rm -rf "$SAGE_ROOT/devel/ext-main-old"
    mv "$SAGE_ROOT/devel/ext-main" "$SAGE_ROOT/devel/ext-main-old"
    if [ $? -ne 0 ]; then
        echo >&2 "Error moving the old 'ext-main' branch."
        exit 1
    fi
fi

rm -f "$SAGE_ROOT/devel/ext" # Delete just the link itself (if it exists)

mkdir -p "$SAGE_ROOT/devel/ext-main"
cp -pR * "$SAGE_ROOT/devel/ext-main/" # Creates new ext-main dir
if [ $? -ne 0 ]; then
    echo >&2 "Error copying the new extcode package."
    exit 1
fi

cp -pR .hg* "$SAGE_ROOT/devel/ext-main/" || exit $?
# Create an appropriate hgrc file for the target
echo -e "[diff]\ngit = true" > "$SAGE_ROOT/devel/ext-main/.hg/hgrc"

ln -s ext-main "$SAGE_ROOT/devel/ext" # Create new symbolic link (deleted above)
if [ $? -ne 0 ]; then
    echo >&2 "Error creating symbolic link to '$SAGE_ROOT/devel/ext-main'."
    exit 1
fi

rm -f "$SAGE_EXTCODE"
mkdir -p "$SAGE_SHARE/sage"
ln -s ../../../devel/ext "$SAGE_EXTCODE"
