from equations import SymbolicEquation
from calculus import (SER,
                      var,
                      sin, cos, sec, tan, log, erf, sqrt, asin, acos, atan, abs)

from calculus import (a,
                      b,
                      c,
                      d,
                      f,
                      g,
                      h,
                      i,
                      j,
                      k,
                      l,
                      m,
                      n,
                      o,
                      p,
                      q,
                      r,
                      s,
                      t,
                      u,
                      v,
                      w,
                      x,
                      y,
                      z,
                      A,
                      B,
                      C,
                      D,
                      E,
                      F,
                      G,
                      H,
                      I,
                      J,
                      K,
                      L,
                      M,
                      N,
                      #O,
                      P,
                      Q,
                      R,
                      S,
                      T,
                      U,
                      V,
                      W,
                      X,
                      Y,
                      Z)




from functional import (diff, solve, integrate)
