#! /usr/bin/env sage -python

import sys, os
from sage.all import *

inn=open("table.sage",'r')
out=open("branching_rules",'w')
verbose = true

for line in inn.readlines():
    if line[0] == '#':
        Rtype = CartanType(line[2:].strip())
        d = []
    elif line[0] == '\n':
        out.write("""    if CartanType(type) == CartanType("%s"):\n"""%Rtype._repr_(compact=true))
        for i in range(len(d)):
            if i == 0:
                out.write("""        ret = [""")
            else:
                out.write("""               """)
            out.write("""\"\"\"%s:%s\"\"\""""%(eval(d[i]).Stype()._repr_(compact=true),d[i]))
            if i == len(d)-1:
                out.write("]\n")
            else:
                out.write(", \\\n")
    else:
        rule = line.strip()
        if verbose:
            print rule
        d.append(rule)
    
    
