#! /usr/bin/env sage -python

import sys, os
from sage.all import *

inn=open("table.sage",'r')
out=open("branching_rules",'w')
verbose = true

for line in inn.readlines():
    if line[0] == '#':
        Rtype = CartanType(line[2:].strip())
        d = {}
    elif line[0] == '\n':
        out.write("""    if CartanType(type) == CartanType("%s"):\n"""%Rtype._repr_(compact=true))
        for i in range(len(d.keys())):
            if i == 0:
                out.write("""        return {""")
            else:
                out.write("""                """)
            k = d.keys()[i]
            out.write(""""%s": \"\"\"%s\"\"\""""%(eval(d[k]).Stype()._repr_(compact=true),d[k]))
            if i == len(d.keys())-1:
                out.write("}\n")
            else:
                out.write(", \\\n")
    else:
        rule = line.strip()
        if verbose:
            print rule
        k = eval(rule).Stype()._repr_(compact=true)
        if d.has_key(k):
            print "duplicate key %s => %s"%(eval(rule)._R,eval(rule)._S)
        d[k]=rule
    
    
