#!/bin/sh

if  [ $# = 0 ]; then
    FILE="`whoami`-`date '+%m-%d-%y'`.hg"
    echo "No bundle file name specified.  Using '$FILE'"
else
    FILE=$1
fi

if [ ! -f $HOME/.hgrc ]; then
    echo "First, you should create a file $HOME/.hgrc,"
    echo "with contents like the following:"
    echo ""
    echo "[ui]"
    echo "username = William Stein <wstein@gmail.com>"
    echo ""
    echo "Create $HOME/.hgrc, then rerun bundle."
    exit 1
fi

SERVER="http://sagemath.org/hg/sage-main"

echo "Now contacting the web server $SERVER"
echo "To figure out how to make a bundle containing all your changes."
echo "This bundle, when applied by William Stein, will update the"
echo "official SAGE branch to have all the functionality in this"
echo "branch of SAGE."

hg bundle $FILE $SERVER

echo "The bundle $FILE has now been created.   You can now email it"
echo "to people."
