#!/bin/sh

rm -rf */.doctest */*/.doctest */*/*/.doctest */*/*/*/.doctest */*/*/*/*/.doctest  */*/*/*/*/*/.doctest

echo "version='"$SAGE_VERSION"'; date='`date '+%Y-%m-%d'`'" > sage/version.py

hg diff

hg status

hg commit

hg tag $1

./mirror
