#!/bin/sh

#######################################
# Install SAGE libraries
#######################################

if [ $? -ne 0 ]; then
   exit 1
fi

DEVEL=$SAGE_ROOT/devel

if [ ! -d "$DEVEL" ]; then
    mkdir "$DEVEL"
fi

if [ $? -ne 0 ]; then
   exit 1
fi

D=`pwd`
E=`basename "$D"`

if [ ! -d "$DEVEL/old" ]; then
    mkdir "$DEVEL/old"
fi

if [ -d "$DEVEL/sage-main" ]; then
    cd "$DEVEL/sage-main"
    hg pull "$SAGE_SERVER"/hg/sage-main
    if [ $? -ne 0 ]; then
        echo "Error pulling in new SAGE source code using hg."
        exit 1
    fi
    "$SAGE_ROOT/sage" -b main
    if [ $? -ne 0 ]; then
        echo "Error building new version of SAGE."
    fi
    exit $?
<fi

mkdir "$DEVEL/sage-main"
cp -pr * "$DEVEL/sage-main/"

sage -b main

if [ $? -ne 0 ]; then
    echo "ERROR installing SAGE"
    exit 1
fi